### ISSUE TITLE
View Results without running them locally?

### ISSUE THREAD

**Issue by ardalis** [danielpalme/DotNetCoverageToolComparision#1]
Can you check in your results or just add screenshots to the README or wiki so it's easy for people to see the results of your comparison without having to install all the various tools in the proper paths and get your batch file to run?

I'm trying to decide if I need altcover or coverlet or something else and the comparison could be useful, but I don't have time to debug why the repo might or might not run properly for me on my machine. Thx and I realize I'm being a bit ungrateful with this request since you've already gone to the trouble of publishing this code.

**Comment by danielpalme** [comment]
The most important file in the repository is `run.bat`.
If you execute this script, the solution is built and the all the tools are executed.

The project title "Comparision" is a bit misleading.
I don't compare the tools in detail. The idea of this repository was, to write down the necessary commands to execute the various tools. This can be found in `run.bat`.

**Comment by ardalis** [comment]
Ok, thanks. I guess the question I have is, should I prefer Coverlet or AltCover or something else? I was misled I guess by the repo name, since there's no comparison given here. :)

Cheers!

**Comment by danielpalme** [comment]
Coverlet or AltCover do almost the same thing.
As far as I know, the _OpenCover_ output of AltCover is a bit more advanced (it also supports tracking by test method).
